version: '2'
services:
    sampleapplication-app:
        image: sampleapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://sampleapplication-mssql:1433;database=SampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sampleapplication-mssql:
        extends:
            file: mssql.yml
            service: sampleapplication-mssql
